name: Python Test and Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Container Build
      id: docker-build
      env:
        DOCKERFILE_PATH: utils/imod/
      run: |
            docker build $DOCKERFILE_PATH
    - name: Container Test
      run: |
            docker run imod dm2mrc -h
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt -y update && sudo apt -y install libgl-dev
    - name: Running pytest
      run: |
        pytest test/

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r docs/requirements.txt
    - name: Build Sphinx Documentation
      run: |
        make -C docs html
    - name: Upload documentation
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: sphinx-docs
        path: docs/_build/html
    - name: Update gh-pages
      if: github.ref == 'refs/heads/main'
      run: |
        rm docs/_build/html/.buildinfo
        touch docs/_build/html/.nojekyll
        git update-ref refs/heads/${TARGET_BRANCH} origin/${TARGET_BRANCH}
        ./.github/workflows/update-gh-pages.sh docs/_build/html
        repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push $repo_uri ${TARGET_BRANCH}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        TARGET_BRANCH: 'gh-pages'
