name: Python Test and Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:


  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r docs/requirements.txt
    - name: Build Sphinx Documentation
      run: |
        make -C docs html
    - name: Upload documentation
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: sphinx-docs
        path: docs/_build/html
    - name: Update gh-pages
      if: github.ref == 'refs/heads/main'
      run: |
        rm docs/_build/html/.buildinfo
        touch docs/_build/html/.nojekyll
        git update-ref refs/heads/${TARGET_BRANCH} origin/${TARGET_BRANCH}
        ./.github/workflows/update-gh-pages.sh docs/_build/html
        repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push $repo_uri ${TARGET_BRANCH}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        TARGET_BRANCH: 'gh-pages'
